<?php
//
// File generated by Dolibarr installer 14.0.3 on Nov 01, 2021
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='https://b2b.deevando.com';
$dolibarr_main_document_root='/var/www/vhosts/deevando.com/b2b';
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt='/var/www/vhosts/deevando.com/b2b/custom';
$dolibarr_main_data_root='/var/www/vhosts/deevando.com/dolibarrdata';
//$dolibarr_main_data_root='/var/www/vhosts/deevando.com/private/dolibarrdata';
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='3306';
$dolibarr_main_db_name='deevando_doli430';
$dolibarr_main_db_prefix='llxas_';
$dolibarr_main_db_user='deevando_doli430';
$dolibarr_main_db_pass='6pS20UG6?_';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_general_ci';
// Authentication settings
$dolibarr_main_authentication='dolibarr';

//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod='0';
$dolibarr_main_force_https='1';
$dolibarr_main_restrict_os_commands='mysqldump, mysql, pg_dump, pgrestore';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_instance_unique_id='3fa501ac3f03ae9b5894abd37e27a595';
$dolibarr_mailing_limit_sendbyweb='0';

//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_TCPDI_PATH='';
//$dolibarr_lib_ADODB_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
$dolibarr_main_distrib='standard';
